### ISSUE TITLE
Calibration randomly jumps frequency

### ISSUE THREAD

**Issue by TimMW1** [ve3wmb/OrionWspr#8]
During calibration  the derived clock frequency of 3.2Mhz randomly jumps.  This seems to correspond to negative counter values.    This may be due to loss of GPS time pulse.  Will need to investigate.

**Comment by ve3wmb** [comment]
TimMW1 

More details are needed, including debug logs, if possible. 

FWIW,  I can't see how it is possible to get negative count values, but it is possible to over-count if 
PPS pulses are delayed due to intermittent GPS PPS signals. We have seen this before and it results in counts that are somewhat bigger than should be expected.  This does have an impact on calibration but it is minimal as the maximum frequency correction per calibration cycle is to about 2 Hz.  The above scenario sometimes happens before detection of GPS LOS. This should be a very
rare occurrence at 10,000+m as GPS LOS (or intermittent LOS)  is not expected to occur frequently.

Michael VE3WMB

**Comment by ve3wmb** [comment]
No further details so this is closed on June 9, 2020
